# to use this, go to ExchangeRateConverter folder type:
# docker-compose build (if any changes)
# docker-compose up
# --------------------------------------
# If need to make changes after up
# docker-compose down
# docker-compose build
# docker-compose up
version: '3'
services:
  springss-app:
    container_name: 'springss-app'
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-database:3306/my-database?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: a
      SPRING_DATASOURCE_PASSWORD: a
    depends_on:
      - my-database
    build: .
  my-database:
    image: mysql:latest
    container_name: 'my-database'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-database
      MYSQL_USER: a
      MYSQL_PASSWORD: a
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 5
